server:
    port: 9000

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

spring:
  application:
      name: GATEWAY-SERVICE
  cloud:
    gateway:
      routes:
          - id: user-service
            uri: http://localhost:8082
            predicates:
            - Path=/users/**
          - id: job-service
            uri: http://localhost:8083
            predicates:
            - Path=/jobs/**
      discovery:
         locator:
           enabled: true
           lower-case-service-id: true



